- name: nginx install and run
  hosts: web
  become: yes #this is for sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package: #hetrogenous module that can work for all distributions ubuntu,red hat ...
      name: nginx
      state: present

- name: run nginx
  ansible.builtin.servive:
    name: nginx
    state: started
    enabled: yes

  tasks:
  - name: mysql install
    ansible.builtin.package:
      name: mysql
      state: present

  - name: run mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes